### ISSUE TITLE
Error: "No inferior python process running"

### ISSUE THREAD

**Issue by rhstanton** [thisch/python-cell.el#10]
I just tried installing this useful-looking package, but when I try to run a cell, I get the error message "No inferior python process running." A more detailed error dump follows:

Debugger entered--Lisp error: (error "No inferior Python process running.")
  signal(error ("No inferior Python process running."))
  error("No inferior Python process running.")
  python-shell-get-process-or-error(nil)
  python-shell-send-region(15 62)
  python-shell-send-cell()
  funcall-interactively(python-shell-send-cell)
  call-interactively(python-shell-send-cell nil nil)
  command-execute(python-shell-send-cell)

Thanks for any suggestions.

**Comment by thisch** [comment]
Hi @rhstanton. I'm currently not using python-cell.el, but I'll test it again in a couple of days. Don't hesitate to ping me.

**Comment by thisch** [comment]
Have you tried running "M-x run-python" before calling `python-shell-send-cell`?

**Comment by rhstanton** [comment]
That works! Thanks.
