### ISSUE TITLE
Can this package show the plot in Emacs shell?

### ISSUE THREAD

**Issue by hongyi-zhao** [thisch/python-cell.el#11]
I think this package can do something similar to [comint-mime](https://github.com/astoff/comint-mime), i.e., displaying graphics and other MIME attachments in Emacs shells, as [commented here](https://github.com/astoff/comint-mime/issues/2#issuecomment-922462074). I do the testing with the following configuration:

```emacs-lisp
(use-package python-cell
  :hook (python-mode . python-cell-mode))  
```
`M-x run-python` then `C-RET`, only see the following result:

![image](https://user-images.githubusercontent.com/11155854/134178873-b52852bd-4e83-4c72-ad63-7af1775b463f.png)

Did I misunderstand the purpose of this package? Any hints will be greatly appreciated.

Regards,
HZ

**Comment by thisch** [comment]
Hi @hongyi-zhao ! If you only want to send the buffer contents to an python process started via `run-python`,  you don't need my `python-cell` pkg for that (type C-c C-c in the python buffer, which calls `python-shell-send-buffer`).

I've just tested the code in your example and in my case the matplotlib plot window is displayed. In case you haven't already solved this issue, does it work if you run the python code outside of emacs (I guess this doesn't make a difference, but just to be sure)?

**Comment by hongyi-zhao** [comment]
> I've just tested the code in your example and in my case the matplotlib plot window is displayed. 

What's exact key/command sequences run by you in Emacs to display the matplotlib plot in Emacs buffer?

> does it work if you run the python code outside of emacs


```python
$ cat test.py 
import matplotlib.pyplot as plt
a = [i %2 for i in range(16)]

plt.plot(a)
plt.show()
```

![image](https://user-images.githubusercontent.com/11155854/148149400-754e849a-22b3-472f-ac1d-ce424e8ab5ab.png)

**Comment by thisch** [comment]
> What's exact key/command sequences run by you in Emacs to display the matplotlib plot in Emacs buffer?

I also pressed <kbd>C-return</kbd> in the python buffer in emacs. Can you also try to run the python script from within emacs but   using `M-x ansi-term`? Maybe the issue is somehow related to different environments used on your host and inside emacs.

**Comment by hongyi-zhao** [comment]
> I also pressed C-return in the python buffer in emacs.

I can only see the following:

![image](https://user-images.githubusercontent.com/11155854/148183735-2f2f1d7f-26ab-4897-9f9e-ca08e8c4bcf9.png)

> Can you also try to run the python script from within emacs but using `M-x ansi-term`?

See following:

![image](https://user-images.githubusercontent.com/11155854/148183987-c4d4afd4-360a-40b6-b493-a711e8b7c0be.png)

**Comment by thisch** [comment]
Isn't it sufficient that the graph is displayed in the comint buffer (nice feature of `comint-mime` BTW)?  Anyway, I think this issue is not related to `python-cell.el`, which mainly extends the font-lock-keywords and adds a few commands for navigating between Matlab (or jupyter)-like cells.

**Comment by hongyi-zhao** [comment]
Yep. The feature supplied by `comint-mime` is sufficient. This question comes from some misunderstandings in my mind about the feature set of `python-cell.el`: I think it also implements the related functions of `comint-mime`. Thank you again for your explanation. Got it.
