### ISSUE TITLE
How to set '%%' instead of '##' as cell boundaries?

### ISSUE THREAD

**Issue by JoKeyser** [thisch/python-cell.el#5]
Hi, I like the package a lot, but can't figure out how to change the default cell boundaries. I would like to define `%%`, to match with spyder's definition. (It's probably trivial, but I'm new to Emacs, and don't know Lisp).
The default regex is:
```
^[[:space:]]*\(#\(?:#[[:space:]][^]*\| <\(?:\(?:\(?:code\|markdown\)cell\)\)>\)$\)
```
What *should* it be for my case? Thanks in advance!

**Comment by cpbotha** [comment]
In order to change it to standard for code cells in PyCharm (which should be the same as Spyder), which is `#%% name of cell` I did this in my `init.el`:

``` emacs-lisp
(setq python-cell-cellbreak-regexp
  (rx line-start (* space)
      (group (and "#" (or (and "%%" space (* (not (any "\n"))))
                          (and " <" (or "codecell" "markdowncell") ">"))
                  line-end))))
```

Example result looks like this:

![image](https://user-images.githubusercontent.com/937871/48225526-b88a9900-e3a5-11e8-8d16-dc1890f0471e.png)

**Comment by JoKeyser** [comment]
@cpbotha this looks really promising
Unfortunately my emacs-foo is insufficient to make this run along with my `.spacemacs` configuration. I tried pasting your code into `(defun dotspacemacs/user-init ()` or `(defun dotspacemacs/user-config ()`, but each one throws errors.
Maybe you or somebody else knows how to amend this.

Generally, I still think the regex definition should be an option to this package.

**Comment by cpbotha** [comment]
You have not stated which errors you saw, so I have no chance of diagnosing correctly. :)

However, it is possible that spacemacs does not use =use-package=, in which case you should just stick the =:config= sexp by itself into your config. In other words, add only this bit:

``` emacs-lisp
(setq python-cell-cellbreak-regexp
        (rx line-start (* space)
            (group (and "#" (or (and (* space) "%%" (* space) (* (not (any "\n"))))
                                (and " <" (or "codecell" "markdowncell") ">"))
                        line-end))))
```

Most importantly, you should stick it somewhere AFTER the loading of the python-cell package.

**Comment by JoKeyser** [comment]
@cpbotha sorry for the missing info, your remote diagnosis was on point though: It works for me, thanks a lot!

**Comment by JoKeyser** [comment]
@cpbotha care to write out what the regex should be? I played around with it but couldn't make it work.

**Comment by cpbotha** [comment]
To see that, you can just eval (in the scratch buffer) the value of the whole sub-expression from `(rx ...` onwards.

in my case, it's `^[[:space:]]*\\(#\\(?:[[:space:]]*%%[[:space:]]*[^]*\\| <\\(?:\\(?:\\(?:code\\|markdown\\)cell\\)\\)>\\)$\\)`

**Comment by JoKeyser** [comment]
@cpbotha thanks again. I tried your line, but it results in `Invalid regexp: "Unmatched [ or [^"`. However, introducing a literal newline into the regexp fixes this:
```emacs-lisp
^[[:space:]]*\(#\(?:[[:space:]]*%%[[:space:]]*[^
]*\| <\(?:\(?:\(?:code\|markdown\)cell\)\)>\)$\)
```

To anyone wondering: Note that the line above is what you should enter when you use Emacs `M-x customize-variable` and then select variable `python-cell-cellbreak-regexp`.
After hitting `Apply and Save`, it will change your emacs config file (in my case, `.spacemacs`), like this (note that it escapes the backslashes, `\\`):

```emacs-lisp
(custom-set-variables
;; some other stuff
 '(python-cell-cellbreak-regexp
   "^[[:space:]]*\\(#\\(?:[[:space:]]*%%[[:space:]]*[^
]*\\| <\\(?:\\(?:\\(?:code\\|markdown\\)cell\\)\\)>\\)$\\)")
;; more other stuff
)
```

@cpbotha , I think this is fixed now.
