### ISSUE TITLE
Ctrl-Return doesn't work in a terminal

### ISSUE THREAD

**Issue by bitic** [thisch/python-cell.el#6]
Hi,

I work on a remote machine using emacs. I connect to the remote computer using the cygwin terminal (Windows 10) and mosh.

Control-Return is the default keybiding for sending the cell to the shell. It would be nice if python-cell had another key biding for the case in which it is used within a terminal.

Thanks for the great work.

**Comment by thisch** [comment]
If I remember correctly, the reason why <kbd>Ctrl-Ret</kbd> was chosen as the key-binding for sending a cell to the python interpreter was that MATLAB uses the same key-binding for executing cells.

You can easily customize the key-binding(s) if you don't like the default key-bindings or if they don't work.
